"""Database Creation

Revision ID: 3c9e51089eb4
Revises: 
Create Date: 2025-10-06 10:59:39.432238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9e51089eb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('umore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stato', sa.String(length=80), nullable=False),
    sa.Column('frase', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frase', sa.Text(), nullable=True),
    sa.Column('umore_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['umore_id'], ['umore.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('umore_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['umore_id'], ['umore.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('frase')
    op.drop_table('umore')
    # ### end Alembic commands ###
