"""Column frase deleted from Umore

Revision ID: d01350e01ac5
Revises: 3c9e51089eb4
Create Date: 2025-10-06 11:00:27.271412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01350e01ac5'
down_revision = '3c9e51089eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('umore', schema=None) as batch_op:
        batch_op.drop_column('frase')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('umore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frase', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
